services:
  app:
    build: .
    container_name: biblioteca_app
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=sistema_biblioteca
      - DB_USER=biblioteca_user
      - DB_PASS=biblioteca_pass

  db:
    image: mysql:8.0
    container_name: biblioteca_db
    restart: always
    environment:
      MYSQL_DATABASE: sistema_biblioteca
      MYSQL_USER: biblioteca_user
      MYSQL_PASSWORD: biblioteca_pass
      MYSQL_ROOT_PASSWORD: root_pass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./sistema_biblioteca.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:
